services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./resources:/app/resources
      - ./db:/app/db
      - ./.env:/app/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
