services:
  app:
    build: .
    volumes:
      - db_data:/app/db   # <-- Named Volume, nicht ./db:/app/db
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  db_data:
